#!/usr/bin/env bash

# $1 = run_dir
# $2 = target

new_contents=""
newline=$'\n'

while IFS="" read -r file || [[ -n "$file" ]]
do
    file_dir="$(dirname "$file")"

    if [[ "$file_dir" == "$2"* ]]
    then
        if [[ -f "$file" ]]
        then
            rm "$file"
        fi
    else
        new_contents="$new_contents$file$newline"
    fi
done < "$1/dat/obj"

printf '%s' "$new_contents" > "$1/dat/obj"
