#!/usr/bin/env bash

# $1 = run_dir
# $2 = rule
# $3 = target

skip=false

while IFS="" read -r cmd <&3 || [[ -n "$cmd" ]]
do
    cmd=${cmd//@@/$1}
    cmd=${cmd//@/$3}
    
    cmd_type="${cmd:0:1}"

    if [[ "$cmd_type" == "$" ]]
    then
        mkdir -p "$1/dat"
        touch "$1/dat/obj"

        if [[ "$skip" == false ]] && ! grep -q "$obj" "$1/dat/obj"
        then
            printf "%s\n" "$obj" >> "$1/dat/obj"
        fi

        skip=false
    fi

    if [[ "$cmd_type" == "!" && "$skip" == false ]]
    then
        eval "${cmd:1}" || exit $?
    fi

    if [[ "$cmd_type" == ">" ]]
    then
        read -ra file_arr <<< "${cmd:1}"
        obj=${file_arr[0]}
        pre_array=${file_arr[*]:1}

        need_compile=false

        for pre in ${pre_array[*]}
        do
            if [[ ! -f "$pre" ]]
            then
                printf "Prestiquite '%s' does not exist.\n" "$pre"
                exit 1
            fi

            if [[ ! -f "$obj" || "$pre" -nt "$obj" ]]
            then
                need_compile=true
            fi
        done

        if [[ "$need_compile" == false ]]
        then
            skip=true
        fi
    fi
done 3< "$1/rule/$2"
